### ISSUE TITLE
"failed to encode package relative path" when running kallax

### ISSUE THREAD

**Issue by jakebailey** [myitcv/gobin#64] opened 2019-02-24 19:45 UTC
I have a project I'm trying to convert to modules, and am using `gobin` to manage the binaries I use in `go generate`. However, one of those dependencies doesn't seem to be able to be run with `gobin`:

```
failed to encode package relative path gopkg.in/src-d/go-kallax.v1/generator/cli/kallax: malformed module path "gopkg.in/src-d/go-kallax.v1/generator/cli/kallax": invalid version
```

Coming from:

```go
//go:generate gobin -m -run gopkg.in/src-d/go-kallax.v1/generator/cli/kallax gen
```

My `tools.go` file looks (roughly) like this:

```go
// +build tools

package tools

import (
	_ "gopkg.in/src-d/go-kallax.v1/generator/cli/kallax"
)
```

The `gopkg.in/src-d/go-kallax.v1` import path is already used in my project in a few places as well, which works normally. I'm not sure if the issue is in `gobin`, or in `go-internals` (looking at where this error message is created).

**Comment by jakebailey** [comment] 2019-02-24 20:08
Hmm, this may not matter at the end of the day (at least for my use) as I've just discovered that `kallax` itself doesn't work when used outside of `$GOPATH`. Oops.

**Comment by myitcv** [comment] 2019-03-21 16:14
_Apologies for the delay in replying, I had closed [Octobox](https://octobox.io/) and so was not receiving notifications for this repo._

Is there still an outstanding issue here? Happy to help if so.

**Comment by jakebailey** [comment] 2019-03-23 01:30
It's still an issue; this is the same as #65. Since kallax doesn't work in module mode anyway, it's not that big of a problem at the end of the day, though.

**Comment by myitcv** [comment] 2019-03-23 08:46
Thanks @jakebailey. I'll close this as a dupe of #65, but I have a fix incoming.

**Closed by myitcv** 2019-03-23 08:46 UTC
